### ISSUE TITLE
New MeSH 2021 P-R questions

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/mapping-project#5]
See below for my NO MATCH and/or questions about potential mapping for P-R terms:
- Persistent Left Superior Vena Cava (D000083402) -> NO MATCH
- Pestalotiopsis (D000084842) -> NO MATCH
- Phoma (D000084723) -> Phoma? (sh88022084) (unsure - the LCSH points to broader term Sphaeropsidaceae, which isn't mentioned in the MESH records - referring to the same thing? I would lean towards no match, as both of these  have different heirarchical relationships within their own vocabularies, but interested in hearing others' thoughts)
- Phomopsis (D000084725) -> Phomopsis? (sh92000224) (same issues as Phoma - see above)
- Photothermal Therapy (D000082703) -> NO MATCH (though possibly BM Fever therapy or Fever therapy + Photochemotherapy, but those combinations don't seem quite right)
- Popliteal Artery Entrapment Syndrome (D000083082) -> NO MATCH (no LSCH for Popliteal Artery)
- Practice Patterns, Pharmacists' (D000086702) -> NO MATCH (or would others BM to Medical care--Utilization review? (https://id.loc.gov/authorities/subjects/sh86004273.html), or use that AND Pharmacists (sh85100592)?)
- Preoperative Exercise (D000082622) -> NO MATCH (doesn't seem to align with either Preoperative education or reoperative care)
- Prolyl Oligopeptidases (D000085822) -> NO MATCH
- Psychosocial Functioning (D000083623) - NO MATCH
- Quick Diagnosis Units (D000084782) -> NO MATCH
- Rappaport (D000086322) -> NO MATCH
- Psychosocial Intervention (D000083626) - NO MATCH? or BT Psychotherapy (sh85108516) (which is the next level up in MeSH tree structure)
- Retinyl Esters (D000084562) -> BM Retenoids (sh85113339) (Question - should I add AND Esters (sh85044949)?)
- Return to School (D000084722) -> NO MATCH
- Rhinorrhea (D000086722) -> NO MATCH (no mapping for next step up "Signs and Symptoms, Respiratory")
- Rhizopus oryzae(D000082763) -> NO MATCH (no mapping for next step up "Rhizopus")
- Routinely Collected Health Data (D000085143) -> NO MATCH (debated about this one - LC Medical records--Data processing is already mapped to MeSH Medical Records Systems, Computerized, which seems to be about the process/systems of collecting data, not the data itself. Open to feedback, though. Also considering BM to Medical records (sh85083010))

**Comment by gneidhardt** [comment]
Note: I'm trying out assigning folks to see if that works. Sharon et al - feel free to assign others within your system if you'd like!

**Comment by ajolson387** [comment]
I agree with most of the NO MATCH decisions. I would recommend mapping four of the MeSH headings.

Phoma (MeSH) can be mapped to Phoma (LCSH), since both headings are a genus of Fungi.

Also Phomopsis (MeSH) can be mapped to Phomopsis (LCSH) since both headings are a genus of Fungi.

For questions concerning Taxonomic terminology and classification I usually refer to the Integrated Taxonomic Information System, ITIS (https://www,itis.gov) or if necessary Wikipedia.

I would map Practice Patterns, Pharmacists (MeSH) to Pharmacy--Practice (LCSH sh2010106017).

I would map Retinyl Esters (MeSH) to Vitamin A (LCSH sh 85143952) and Esters (LCSH sh 85044949). Note that retinol is a synonym for Vitamin A.

Let me know if you have any questions.

**Comment by gneidhardt** [comment]
Accepted Tony's suggestions and have updated main files as indicated.
